package com.wysiwyg.temanolga.utils

class CityUtil{
    companion object {
        val city = arrayOf ("Kota Langsa",
            "Kota Lhokseumawe",
            "Kota Sabang",
            "Kota Banda Aceh",
            "Kab. Bener Meriah",
            "Kab. Aceh Tamiang",
            "Kab. Nagan Jaya",
            "Kab. Aceh Jaya",
            "Kab. Gayo Lues",
            "Kab. Aceh Barat Daya",
            "Kab. Bireun",
            "Kab. Aceh Singkil",
            "Kab. Simeulue",
            "Kab. Aceh Utara",
            "Kab. Pidie",
            "Kab. Aceh Besar",
            "Kab. Aceh Barat",
            "Kab. Tengah",
            "Kab. Aceh Timur",
            "Kab. Aceh Tenggara",
            "Kab. Aceh Selatan",
            "Kota Padang Sidempuan",
            "Kota Tebing Tinggi",
            "Kota Binjai",
            "Kota Tanjung Balai",
            "Kota Sibolga",
            "Kota Pematang Siantar",
            "Kota Medan",
            "Kab. Serdang Bedagai ",
            "Kab. Samosir ",
            "Kab. Humbang Hasundutan",
            "Kab. Pakpak Barat",
            "Kab. Nias Selatan",
            "Kab. Mandailing Natal",
            "Kab. Toba Samosir",
            "Kab. Dairi",
            "Kab. Labuhan Batu",
            "Kab. Asahan",
            "Kab. Simalungun",
            "Kab. Deli Serdang",
            "Kab. Karo",
            "Kab. Langkat",
            "Kab. Nias",
            "Kab. Tapanuli Selatan",
            "Kab. Tapanuli Utara",
            "Kab. Tapanuli Tengah",
            "Kota Pariaman",
            "Kota Payakumbuh",
            "Kota Bukittinggi",
            "Kota Padang Panjang",
            "Kota Sawhlunto",
            "Kota Solok",
            "Kota Padang",
            "Kab. Pasaman Barat ",
            "Kab. Solok Selatan ",
            "Kab. Dharmasraya",
            "Kab. Kepulauan Mentawai",
            "Kab. Pasaman ",
            "Kab. Lima Puluh Kota",
            "Kab. Agam",
            "Kab. Padang Pariaman",
            "Kab. Tanah Datar",
            "Kab. Sw.lunto",
            "Kab. Solok",
            "Kab.pesisir Selatan",
            "Kota Dumai",
            "Kota Pekan Baru",
            "Kab. Kuantan Singingi",
            "Kab. Siak",
            "Kab. Rokan Hilir",
            "Kab. Rokan Hulu",
            "Kab. Pelalawan",
            "Kab. Indragiri Hilir",
            "Kab. Bengkalis",
            "Kab. Indragiri Hulu",
            "Kab. Kampar",
            "Kab. Kerinci",
            "Kab. Tebo",
            "Kab. Bungo",
            "Kab. Tanjung Jabung Timur",
            "Kab. Tanjung Jabung Barat",
            "Kab. Muaro Jambi",
            "Kab. Batanghari",
            "Kab. Sarolangun",
            "Kab. Merangin",
            "Kota Jambi",
            "Kota Prabumulih",
            "Kota Lubuk Linggau",
            "Kota Pagar Alam",
            "Kota Palembang",
            "Kab. Ogan Ilir ",
            "Kab. Oku Selatan ",
            "Kab. Oku Timur ",
            "Kab. Banyuasin",
            "Kab. Musi Banyuasin",
            "Kab. Musi Rawas",
            "Kab. Lahat",
            "Kab. Muara Enim",
            "Kab. Ogan Komering Ilir ",
            "Kab. Ogan Komering Ulu",
            "Kota Bengkulu",
            "Kab. Kepahiang ",
            "Kab. Lebong ",
            "Kab. Muko Muko",
            "Kab. Seluma",
            "Kab. Kaur",
            "Kab. Bengkulu Utara",
            "Kab. Rejang Lebong ",
            "Kab. Bengkulu Selatan",
            "Kota Metro",
            "Kota Bandar Lampung",
            "Kab. Way Kanan",
            "Kab. Lampung Timur",
            "Kab. Tanggamus",
            "Kab. Tulang Bawang",
            "Kab. Lampung Barat",
            "Kab. Lampung Utara",
            "Kab. Lampung Tengah",
            "Kab. Lampung Selatan",
            "Kota Pangkal Pinang",
            "Kab. Bangka Timur",
            "Kab. Bangka Barat",
            "Kab. Bangka Tengah",
            "Kab. Bangka Selatan",
            "Kab. Belitung",
            "Kab. Bangka",
            "Kota Tanjung Pinang",
            "Kota Batam",
            "Kab. Lingga ",
            "Kab. Natuna",
            "Kab. Karimun",
            "Kab. Kepulauan Riau",
            "Kota Jakarta Timur",
            "Kota Jakarta Selatan",
            "Kota Jakarta Barat",
            "Kota Jakarta Utara",
            "Kota Jakarta Pusat",
            "Kepulauan Seribu",
            "Kota Banjar",
            "Kota Tasikmalaya",
            "Kota Cimahi",
            "Kota Depok",
            "Kota Bekasi",
            "Kota Cirebon",
            "Kota Bandung",
            "Kota Sukabumi",
            "Kota Bogor",
            "Kab. Bekasi",
            "Kab. Karawang",
            "Kab. Purwakarta",
            "Kab. Subang",
            "Kab. Indramayu",
            "Kab. Sumedang",
            "Kab. Majalengka",
            "Kab. Cirebon",
            "Kab. Kuningan",
            "Kab. Ciamis",
            "Kab. Tasikmalaya",
            "Kab. Garut",
            "Kab. Bandung",
            "Kab. Bandung Barat",
            "Kab. Cianjur",
            "Kab. Sukabumi",
            "Kab. Bogor",
            "Kota Tegal",
            "Kota Pekalongan",
            "Kota Semarang",
            "Kota Salatiga",
            "Kota Surakarta",
            "Kota Magelang",
            "Kab. Brebes",
            "Kab. Tegal",
            "Kab. Pemalang",
            "Kab. Pekalongan",
            "Kab. Batang",
            "Kab. Kendal",
            "Kab. Temanggung",
            "Kab. Semarang",
            "Kab. Demak",
            "Kab. Jepara",
            "Kab. Kudus",
            "Kab. Pati",
            "Kab. Rembang",
            "Kab. Blora",
            "Kab. Grobogan",
            "Kab. Sragen",
            "Kab. Karanganyar",
            "Kab. Wonogiri",
            "Kab. Sukoharjo",
            "Kab. Klaten",
            "Kab. Boyolali",
            "Kab. Magelang",
            "Kab. Wonosobo",
            "Kab. Purworejo",
            "Kab. Kebumen",
            "Kab. Banjarnegara",
            "Kab. Purbalingga",
            "Kab. Banyumas",
            "Kab. Cilacap",
            "Kota Yogyakarta",
            "Kab. Sleman",
            "Kab. Gunung Kidul",
            "Kab. Bantul",
            "Kab. Kulon Progo",
            "Batu",
            "Kota Surabaya",
            "Kota Madiun",
            "Kota Mojokerto",
            "Kota Pasuruan",
            "Kota Probolinggo",
            "Kota Malang",
            "Kota Blitar",
            "Kota Kediri",
            "Kab. Sumenep",
            "Kab. Pamekasan",
            "Kab. Sampang",
            "Kab. Bangkalan",
            "Kab. Gresik",
            "Kab. Lamongan",
            "Kab. Tuban",
            "Kab. Bojonegoro",
            "Kab. Ngawi",
            "Kab. Magetan",
            "Kab. Madiun",
            "Kab. Nganjuk",
            "Kab. Jombang",
            "Kab. Mojokerto",
            "Kab. Sidoarjo",
            "Kab. Pasuruan",
            "Kab. Probolinggo",
            "Kab. Situbondo",
            "Kab. Bondowoso",
            "Kab. Banyuwangi",
            "Kab. Jember",
            "Kab. Lumajang",
            "Kab. Malang",
            "Kab. Kediri",
            "Kab. Blitar",
            "Kab. Tulungagung",
            "Kab. Trenggalek",
            "Kab. Ponorogo",
            "Kab. Pacitan",
            "Kota Cilegon",
            "Kota Tangerang",
            "Kab. Serang",
            "Kab. Tangerang",
            "Kab. Lebak",
            "Kab. Pandeglang",
            "Kota Denpasar",
            "Kab. Buleleng",
            "Kab. Karangasem",
            "Kab. Bangli",
            "Kab. Klungkung",
            "Kab. Gianyar",
            "Kab. Badung",
            "Kab. Tabanan",
            "Kab. Jembarana",
            "Kota Bima",
            "Kota Mataram",
            "Kab. Sumbawa Barat",
            "Kab. Bima",
            "Kab. Dompu",
            "Kab. Sumbawa ",
            "Kab. Lombok Timur",
            "Kab. Lombok Tengah",
            "Kab. Lombok Barat",
            "Kota Kupang",
            "Kab. Manggarai Barat",
            "Kab. Rote Ndao",
            "Kab. Lembata",
            "Kab. Sumba Barat",
            "Kab. Sumba Timur",
            "Kab. Manggarai",
            "Kab. Ngada",
            "Kab. Ende",
            "Kab. Sikka",
            "Kab. Flores Timur",
            "Kab. Alor",
            "Kab. Belu",
            "Kab. Timor Tengah Utara",
            "Kab. Timor Tengah Selatan",
            "Kab. Kupang",
            "Kota Singkawang",
            "Kota Pontianak",
            "Kab. Sekadau",
            "Kab. Melawi",
            "Kab. Landak",
            "Kab. Bengkayang",
            "Kab. Kapuas Hulu",
            "Kab. Sintang ",
            "Kab. Ketapang",
            "Kab. Sanggau ",
            "Kab. Pontianak",
            "Kab. Sambas",
            "Kota Palangkaraya",
            "Kab. Barito Timur",
            "Kab. Murung Raya",
            "Kab. Pulang Pisau",
            "Kab. Gunung Mas",
            "Kab. Lamandau",
            "Kab. Sukamara",
            "Kab. Seruyan",
            "Kab. Katingin",
            "Kab. Barito Utara",
            "Kab. Barito Selatan",
            "Kab. Kapuas",
            "Kab. Kotawaringin Timur",
            "Kab. Kotawaringin Barat",
            "Kota Banjarbaru",
            "Kota Banjarmasin",
            "Kab. Balangan",
            "Kab. Tanah Bambu",
            "Kab. Tabalong",
            "Kab. Hulu Sungai Utara",
            "Kab. Hulu Sungai Tengah",
            "Kab. Hulu Sungai Selatan",
            "Kab. Tapin",
            "Kab. Barito Kuala",
            "Kab. Banjar",
            "Kab. Kotabaru",
            "Kab. Tanah Laut",
            "Kota Bontang",
            "Kota Tarakan",
            "Kota Samarinda",
            "Kota Balikpapan",
            "Kab. Penajam Paser Utara",
            "Kab. Kutai Timur",
            "Kab. Kutai Barat",
            "Kab. Malinau",
            "Kab. Nunukan",
            "Kab. Bulungan",
            "Kab. Berau",
            "Kab. Kutai Kertanegara",
            "Kab. Pasir",
            "Kota Tomohon",
            "Kota Bitung",
            "Kota Manado",
            "Kab. Minahasa Utara",
            "Kab. Minahasa Selatan",
            "Kab. Kepulauan Talaud",
            "Kab. Kepulauan Sangihe",
            "Kab. Minahasa ",
            "Kab. Bolaang Mangondow",
            "Kota Palu",
            "Kab. Tojo Una Una",
            "Kab. Parigi Moutong",
            "Kab. Banggai Kepulauan",
            "Kab. Morowali",
            "Kab. Buol",
            "Kab. Toloi Toli",
            "Kab. Donggala",
            "Kab. Poso ",
            "Kab. Banggai",
            "Kota Palopo",
            "Kota Pare Pare",
            "Kota Makasar",
            "Kab. Luwu Timur",
            "Kab. Luwu Utara",
            "Kab. Tana Toraja",
            "Kab. Luwu",
            "Kab. Enrekang",
            "Kab. Pinrang",
            "Kab. Sidenreng Rapang",
            "Kab. Wajo",
            "Kab. Soppeng",
            "Kab. Barru",
            "Kab. Pangkajene Kep.",
            "Kab. Maros",
            "Kab. Bone",
            "Kab. Sinjai",
            "Kab. Gowa",
            "Kab. Takalar",
            "Kab. Jeneponto.",
            "Kab. Bantaeng",
            "Kab. Bulukumba",
            "Kab. Selayar",
            "Kota Bau Bau",
            "Kota Kendari",
            "Kab. Kolaka Utara",
            "Kab. Wakatobi",
            "Kab. Bombana",
            "Kab. Konawe Selatan",
            "Kab. Buton",
            "Kab. Muna",
            "Kab. Konawe",
            "Kab. Kolaka",
            "Kota Gorontalo",
            "Kab. Pahuwato",
            "Kab. Bone Bolango",
            "Kab. Boalemo",
            "Kab. Gorontalo",
            "Kab. Majene",
            "Kab. Polowali Mamasa",
            "Kab. Mamasa",
            "Kab. Mamuju",
            "Kab. Mamuju Utara",
            "Kota Ambon",
            "Kab. Kepulauan Aru",
            "Kab. Seram Bagian Barat ",
            "Kab. Seram Bagian Timur",
            "Kab. Buru",
            "Kab. Maluku Tenggara Barat",
            "Kab. Maluku Tenggara",
            "Kab. Maluku Tengah",
            "Kota Tidore Kepulauan",
            "Kota Ternate",
            "Kab. Halmahera Timur",
            "Kab. Kepulauan Sula",
            "Kab. Halmahera Selatan",
            "Kab. Halmahera Utara",
            "Kab. Halmahera Tengah",
            "Kab. Halmahera Barat",
            "Kota Jayapura",
            "Kab. Supiori",
            "Kab. Asmat",
            "Kab. Mappi",
            "Kab. Boven Digoel",
            "Kab. Waropen",
            "Kab. Tolikara",
            "Kab. Yahukimo",
            "Kab. Pegunungan Bintang",
            "Kab. Keerom",
            "Kab. Sarmi",
            "Kab. Mimika",
            "Kab. Paniai",
            "Kab. Puncak Jaya",
            "Kab. Biak Numfor",
            "Kab. Yapen Waropen",
            "Kab. Nabire",
            "Kab. Jayapura",
            "Kab. Jayawijaya",
            "Kab. Merauke",
            "Kota Sorong",
            "Kab. Kaima",
            "Kab. Teluk Wondama",
            "Kab. Teluk Bentuni",
            "Kab. Raja Ampat",
            "Kab. Sorong Selatan",
            "Kab. Fak Fak",
            "Kab. Manokwari",
            "Kab. Sorong")
    }
}